name: Pull Request Build & Test

on: pull_request

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Test and Build
        run: |
          yarn
          yarn lint
          yarn test
          yarn build
