name: Release

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    environment: npm
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.LIFEOMIC_NPM_TOKEN }}
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Test and Build
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          npm -v
          yarn
          yarn lint
          yarn test
          yarn build
      - name: Publish
        run: |
          yarn semantic-release
